language: generic
os: osx
matrix:
  include:
    - os: linux
      dist: precise
      env: CC=gcc-5
      addons:
        apt:
          packages:
            - gcc-5
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
    - os: linux
      dist: precise
      env: CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$CC .. && make
