language: generic
matrix:
  include:
    - os: linux
      dist: precise
      env: CC=gcc-5
      addons:
        apt:
          packages:
            - gcc-5
            - cmake
            - cmake-data
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
    - os: linux
      dist: precise
      env: CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - cmake
            - cmake-data
          sources: *sources
    - os: osx
      osx_image: xcode8
      env: CC=clang

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_C_COMPILER=$CC .. && make
